//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bills", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Bills : object
    {
        
        private string DescriptionField;
        
        private int ErrorCodeField;
        
        private System.Collections.Generic.List<PostService.Bill> ListField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<PostService.Bill> List
        {
            get
            {
                return this.ListField;
            }
            set
            {
                this.ListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Bill : object
    {
        
        private int AmountField;
        
        private string DateField;
        
        private string DepositCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DepositCode
        {
            get
            {
                return this.DepositCodeField;
            }
            set
            {
                this.DepositCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StuffDto", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class StuffDto : object
    {
        
        private int IDField;
        
        private int PriceField;
        
        private string TitleField;
        
        private int WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryPrice", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class DeliveryPrice : object
    {
        
        private string DescriptionField;
        
        private int ErrorCodeField;
        
        private int PostDeliveryPriceField;
        
        private int VatTaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostDeliveryPrice
        {
            get
            {
                return this.PostDeliveryPriceField;
            }
            set
            {
                this.PostDeliveryPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VatTax
        {
            get
            {
                return this.VatTaxField;
            }
            set
            {
                this.VatTaxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryMultiPrice", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class DeliveryMultiPrice : object
    {
        
        private int EMSDeliveryPriceField;
        
        private int EMSDeliveryPriceCODField;
        
        private string EMSDescriptionField;
        
        private int EMSErrorCodeField;
        
        private int EMSVatTaxField;
        
        private int RMSDeliveryPriceField;
        
        private int RMSDeliveryPriceCODField;
        
        private string RMSDescriptionField;
        
        private int RMSErrorCodeField;
        
        private int RMSVatTaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMSDeliveryPrice
        {
            get
            {
                return this.EMSDeliveryPriceField;
            }
            set
            {
                this.EMSDeliveryPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMSDeliveryPriceCOD
        {
            get
            {
                return this.EMSDeliveryPriceCODField;
            }
            set
            {
                this.EMSDeliveryPriceCODField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMSDescription
        {
            get
            {
                return this.EMSDescriptionField;
            }
            set
            {
                this.EMSDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMSErrorCode
        {
            get
            {
                return this.EMSErrorCodeField;
            }
            set
            {
                this.EMSErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EMSVatTax
        {
            get
            {
                return this.EMSVatTaxField;
            }
            set
            {
                this.EMSVatTaxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RMSDeliveryPrice
        {
            get
            {
                return this.RMSDeliveryPriceField;
            }
            set
            {
                this.RMSDeliveryPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RMSDeliveryPriceCOD
        {
            get
            {
                return this.RMSDeliveryPriceCODField;
            }
            set
            {
                this.RMSDeliveryPriceCODField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RMSDescription
        {
            get
            {
                return this.RMSDescriptionField;
            }
            set
            {
                this.RMSDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RMSErrorCode
        {
            get
            {
                return this.RMSErrorCodeField;
            }
            set
            {
                this.RMSErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RMSVatTax
        {
            get
            {
                return this.RMSVatTaxField;
            }
            set
            {
                this.RMSVatTaxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TempProducts", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TempProducts : object
    {
        
        private int CountField;
        
        private int DisCountField;
        
        private int IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DisCount
        {
            get
            {
                return this.DisCountField;
            }
            set
            {
                this.DisCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Parcel", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Parcel : object
    {
        
        private string DescriptionField;
        
        private int ErrorCodeField;
        
        private string ParcelCodeField;
        
        private int PostDeliveryPriceField;
        
        private int VatTaxField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParcelCode
        {
            get
            {
                return this.ParcelCodeField;
            }
            set
            {
                this.ParcelCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PostDeliveryPrice
        {
            get
            {
                return this.PostDeliveryPriceField;
            }
            set
            {
                this.PostDeliveryPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VatTax
        {
            get
            {
                return this.VatTaxField;
            }
            set
            {
                this.VatTaxField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class State : object
    {
        
        private int CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class City : object
    {
        
        private int CodeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City2", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class City2 : object
    {
        
        private int CityIDField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CityID
        {
            get
            {
                return this.CityIDField;
            }
            set
            {
                this.CityIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MakeParcelsReadyStatus", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class MakeParcelsReadyStatus : object
    {
        
        private string DescriptionField;
        
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Stuff", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class Stuff : object
    {
        
        private int CountField;
        
        private string DescriptionField;
        
        private int IDField;
        
        private string NameField;
        
        private int PriceField;
        
        private int WeightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Count
        {
            get
            {
                return this.CountField;
            }
            set
            {
                this.CountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputStuff", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class OutputStuff : object
    {
        
        private int ErrorCodeField;
        
        private string ErrorMessageField;
        
        private string NameField;
        
        private int idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode
        {
            get
            {
                return this.ErrorCodeField;
            }
            set
            {
                this.ErrorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage
        {
            get
            {
                return this.ErrorMessageField;
            }
            set
            {
                this.ErrorMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostService.IEshopService")]
    public interface IEshopService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/Billing", ReplyAction="http://tempuri.org/IEshopService/BillingResponse")]
        System.Threading.Tasks.Task<PostService.Bills> BillingAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetStatus", ReplyAction="http://tempuri.org/IEshopService/GetStatusResponse")]
        System.Threading.Tasks.Task<int> GetStatusAsync(string username, string password, string parcelCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetStuffs", ReplyAction="http://tempuri.org/IEshopService/GetStuffsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.StuffDto>> GetStuffsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetDeliveryPrice", ReplyAction="http://tempuri.org/IEshopService/GetDeliveryPriceResponse")]
        System.Threading.Tasks.Task<PostService.DeliveryPrice> GetDeliveryPriceAsync(string username, string password, int cityCode, int price, int weight, int serviceType, int payType, int toCityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetDeliveryMultiPrice", ReplyAction="http://tempuri.org/IEshopService/GetDeliveryMultiPriceResponse")]
        System.Threading.Tasks.Task<PostService.DeliveryMultiPrice> GetDeliveryMultiPriceAsync(string username, string password, int cityCode, int Price, int Weight, int toCityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/AddParcel", ReplyAction="http://tempuri.org/IEshopService/AddParcelResponse")]
        System.Threading.Tasks.Task<PostService.Parcel> AddParcelAsync(string username, string password, System.Collections.Generic.List<PostService.TempProducts> productsId, int cityCode, int serviceType, int payType, string registerFirstName, string registerLastName, string registerAddress, string registerPhoneNumber, string registerMobile, string registerPostalCode, int toCityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/AddParcelWithDiscount", ReplyAction="http://tempuri.org/IEshopService/AddParcelWithDiscountResponse")]
        System.Threading.Tasks.Task<PostService.Parcel> AddParcelWithDiscountAsync(string username, string password, System.Collections.Generic.List<PostService.TempProducts> productsId, int cityCode, int serviceType, int payType, string registerFirstName, string registerLastName, string registerAddress, string registerPhoneNumber, string registerMobile, string registerPostalCode, int disCount, int toCityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/AddParcelPercentDiscount", ReplyAction="http://tempuri.org/IEshopService/AddParcelPercentDiscountResponse")]
        System.Threading.Tasks.Task<PostService.Parcel> AddParcelPercentDiscountAsync(string username, string password, System.Collections.Generic.List<PostService.TempProducts> productsId, int cityCode, int serviceType, int payType, string registerFirstName, string registerLastName, string registerAddress, string registerPhoneNumber, string registerMobile, string registerPostalCode, int disCountPercent, int toCityID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetStates", ReplyAction="http://tempuri.org/IEshopService/GetStatesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.State>> GetStatesAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetCities", ReplyAction="http://tempuri.org/IEshopService/GetCitiesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.City>> GetCitiesAsync(string username, string password, int stateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/GetCities2", ReplyAction="http://tempuri.org/IEshopService/GetCities2Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.City2>> GetCities2Async(string username, string password, int stateId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/ReadyToShip", ReplyAction="http://tempuri.org/IEshopService/ReadyToShipResponse")]
        System.Threading.Tasks.Task<PostService.MakeParcelsReadyStatus> ReadyToShipAsync(string username, string password, string parcelCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/AddStuff", ReplyAction="http://tempuri.org/IEshopService/AddStuffResponse")]
        System.Threading.Tasks.Task<int> AddStuffAsync(string username, string password, string name, int price, int weight, int count, string description, int percentDiscount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/AddStuffs", ReplyAction="http://tempuri.org/IEshopService/AddStuffsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.OutputStuff>> AddStuffsAsync(string username, string password, System.Collections.Generic.List<PostService.Stuff> stuffs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/EditStuffs", ReplyAction="http://tempuri.org/IEshopService/EditStuffsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.OutputStuff>> EditStuffsAsync(string username, string password, System.Collections.Generic.List<PostService.Stuff> stuffs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/EditStuffWeight", ReplyAction="http://tempuri.org/IEshopService/EditStuffWeightResponse")]
        System.Threading.Tasks.Task<int> EditStuffWeightAsync(string username, string password, int stuffId, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEshopService/EditStuffPrice", ReplyAction="http://tempuri.org/IEshopService/EditStuffPriceResponse")]
        System.Threading.Tasks.Task<int> EditStuffPriceAsync(string username, string password, int stuffId, int price);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IEshopServiceChannel : PostService.IEshopService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class EshopServiceClient : System.ServiceModel.ClientBase<PostService.IEshopService>, PostService.IEshopService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public EshopServiceClient() : 
                base(EshopServiceClient.GetDefaultBinding(), EshopServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IEshopService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EshopServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(EshopServiceClient.GetBindingForEndpoint(endpointConfiguration), EshopServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EshopServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(EshopServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EshopServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(EshopServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public EshopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<PostService.Bills> BillingAsync(string username, string password)
        {
            return base.Channel.BillingAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetStatusAsync(string username, string password, string parcelCode)
        {
            return base.Channel.GetStatusAsync(username, password, parcelCode);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.StuffDto>> GetStuffsAsync(string username, string password)
        {
            return base.Channel.GetStuffsAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<PostService.DeliveryPrice> GetDeliveryPriceAsync(string username, string password, int cityCode, int price, int weight, int serviceType, int payType, int toCityID)
        {
            return base.Channel.GetDeliveryPriceAsync(username, password, cityCode, price, weight, serviceType, payType, toCityID);
        }
        
        public System.Threading.Tasks.Task<PostService.DeliveryMultiPrice> GetDeliveryMultiPriceAsync(string username, string password, int cityCode, int Price, int Weight, int toCityID)
        {
            return base.Channel.GetDeliveryMultiPriceAsync(username, password, cityCode, Price, Weight, toCityID);
        }
        
        public System.Threading.Tasks.Task<PostService.Parcel> AddParcelAsync(string username, string password, System.Collections.Generic.List<PostService.TempProducts> productsId, int cityCode, int serviceType, int payType, string registerFirstName, string registerLastName, string registerAddress, string registerPhoneNumber, string registerMobile, string registerPostalCode, int toCityID)
        {
            return base.Channel.AddParcelAsync(username, password, productsId, cityCode, serviceType, payType, registerFirstName, registerLastName, registerAddress, registerPhoneNumber, registerMobile, registerPostalCode, toCityID);
        }
        
        public System.Threading.Tasks.Task<PostService.Parcel> AddParcelWithDiscountAsync(string username, string password, System.Collections.Generic.List<PostService.TempProducts> productsId, int cityCode, int serviceType, int payType, string registerFirstName, string registerLastName, string registerAddress, string registerPhoneNumber, string registerMobile, string registerPostalCode, int disCount, int toCityID)
        {
            return base.Channel.AddParcelWithDiscountAsync(username, password, productsId, cityCode, serviceType, payType, registerFirstName, registerLastName, registerAddress, registerPhoneNumber, registerMobile, registerPostalCode, disCount, toCityID);
        }
        
        public System.Threading.Tasks.Task<PostService.Parcel> AddParcelPercentDiscountAsync(string username, string password, System.Collections.Generic.List<PostService.TempProducts> productsId, int cityCode, int serviceType, int payType, string registerFirstName, string registerLastName, string registerAddress, string registerPhoneNumber, string registerMobile, string registerPostalCode, int disCountPercent, int toCityID)
        {
            return base.Channel.AddParcelPercentDiscountAsync(username, password, productsId, cityCode, serviceType, payType, registerFirstName, registerLastName, registerAddress, registerPhoneNumber, registerMobile, registerPostalCode, disCountPercent, toCityID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.State>> GetStatesAsync(string username, string password)
        {
            return base.Channel.GetStatesAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.City>> GetCitiesAsync(string username, string password, int stateId)
        {
            return base.Channel.GetCitiesAsync(username, password, stateId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.City2>> GetCities2Async(string username, string password, int stateId)
        {
            return base.Channel.GetCities2Async(username, password, stateId);
        }
        
        public System.Threading.Tasks.Task<PostService.MakeParcelsReadyStatus> ReadyToShipAsync(string username, string password, string parcelCode)
        {
            return base.Channel.ReadyToShipAsync(username, password, parcelCode);
        }
        
        public System.Threading.Tasks.Task<int> AddStuffAsync(string username, string password, string name, int price, int weight, int count, string description, int percentDiscount)
        {
            return base.Channel.AddStuffAsync(username, password, name, price, weight, count, description, percentDiscount);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.OutputStuff>> AddStuffsAsync(string username, string password, System.Collections.Generic.List<PostService.Stuff> stuffs)
        {
            return base.Channel.AddStuffsAsync(username, password, stuffs);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<PostService.OutputStuff>> EditStuffsAsync(string username, string password, System.Collections.Generic.List<PostService.Stuff> stuffs)
        {
            return base.Channel.EditStuffsAsync(username, password, stuffs);
        }
        
        public System.Threading.Tasks.Task<int> EditStuffWeightAsync(string username, string password, int stuffId, int weight)
        {
            return base.Channel.EditStuffWeightAsync(username, password, stuffId, weight);
        }
        
        public System.Threading.Tasks.Task<int> EditStuffPriceAsync(string username, string password, int stuffId, int price)
        {
            return base.Channel.EditStuffPriceAsync(username, password, stuffId, price);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEshopService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IEshopService))
            {
                return new System.ServiceModel.EndpointAddress("http://svc.ebazaar-post.ir/EshopService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EshopServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IEshopService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EshopServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IEshopService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IEshopService,
        }
    }
}
